Repository cse110-sp25-group29/cse110-sp25-group29, pull requests merged in 2025-05, with the labels that each got.

#25 Completed documentation and feature issue templates
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/team-assignment.md
  .gitignore
Labels: documentation

#63 ADR - UI/UIX Meeting 1 - 08/05/25
  specs/adrs/05-08-25-UIUX-Homepage-Decision.md
Labels: documentation, home page, ui/ux

#65 Add 5/16 UI/UX meeting notes
  admin/meetings/ui-ux/051625-meeting.md
  admin/meetings/ui-ux/images/051625-progress.png
  admin/meetings/ui-ux/images/all-cards-0.png
  admin/meetings/ui-ux/images/editor-page-0.png
  admin/meetings/ui-ux/images/editor-page-1.png
  admin/meetings/ui-ux/images/landing-page-0.png
  admin/meetings/ui-ux/images/landing-page-1.png
  admin/meetings/ui-ux/images/theme-colors.png
  admin/meetings/ui-ux/images/upload-card-1.png
  admin/meetings/ui-ux/images/wireframe-iter-2.png
  admin/meetings/ui-ux/images/your-card-0.png
  admin/meetings/ui-ux/images/your-card-1.png
Labels: documentation, ui/ux

#66 Cleaning repo structure
  README.md
  source/static/images/issue-history-example.png
  source/static/images/issue-proj-board-example.png
Labels: enhancement

#74 Added standup template for standups. Closes #73
  admin/meetings/standup/mmddyy-standup.md
Labels: documentation

#95 Repo cleanup & docs update
  README.md
  admin/meetings/img/051625-progress.png
  admin/meetings/img/Wireframe.png
  admin/meetings/img/all-cards-0.png
  admin/meetings/img/editor-page-0.png
  admin/meetings/img/editor-page-1.png
  admin/meetings/img/landing-page-0.png
  admin/meetings/img/landing-page-1.png
  admin/meetings/img/logo concept.png
  admin/meetings/img/sarah example.png
  admin/meetings/img/theme-colors.png
  admin/meetings/img/upload-card-1.png
  admin/meetings/img/wireframe-iter-2.png
  admin/meetings/img/your-card-0.png
  admin/meetings/img/your-card-1.png
  admin/meetings/mmddyy-meeting.md
  admin/meetings/mmddyy-standup.md
  admin/meetings/sprint-0/042425-brainstorm.md
  admin/meetings/sprint-0/042625-brainstorm.md
  admin/meetings/sprint-0/042725-brainstorm.md
  admin/meetings/sprint-0/050625-meeting.md
  admin/meetings/sprint-0/050825-meeting-ui-ux.md
  admin/meetings/sprint-0/05102025-meeting.md
  admin/meetings/sprint-1/051225-meeting-ui-ux.md
  admin/meetings/sprint-1/051225-standup.md
  admin/meetings/sprint-1/051425-meeting-ui-ux.md
  admin/meetings/sprint-1/051425-standup.md
  admin/meetings/sprint-1/051625-meeting-ui-ux.md
  admin/meetings/sprint-1/051625-standup.md
  admin/meetings/sprint-1/051725-sprint-1-retrospective.md
  admin/meetings/sprint-1/051725-sprint-1-review.md
  admin/meetings/sprint-2/052025-standup.md
  admin/meetings/sprint-2/052225-standup.md
  admin/meetings/sprint-2/sprint-planning-2.md
  admin/warmup/warmup.pdf
  specs/style-guide.md
Labels: documentation

#77 Complete Home Page with theme design
  README.md
  source/assets/scripts/homepage.js
  source/assets/scripts/placeholder.txt
  source/assets/styles/homepage.css
  source/assets/styles/placeholder.txt
  source/dark.png
  source/homepage.html
  source/light.png
  source/placeholder.txt
Labels: enhancement, home page

#109 Added images to sprint review notes. Close #106, progress #105
  admin/meetings/img/all-cards-1.png
  admin/meetings/img/all-cards-wip.png
  admin/meetings/img/editor-page-2.png
  admin/meetings/img/landing-page-2a.png
  admin/meetings/img/landing-page-2b.png
  admin/meetings/img/logo-1.png
  admin/meetings/img/title-0.png
  admin/meetings/img/title-1.png
  admin/meetings/img/title-iterations-0-1.png
  admin/meetings/sprint-2/05242025-sprint-2-review.md
Labels: documentation, ui/ux
